org: epicode
app: time-bot
service: time-bot

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  profile: serverless

functions:
  alertDiscounts:
    timeout: 20
    handler: ./src/handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin